# dior-s2anet-s0-trainonly: frozen DIOR-R validation-split check (DESIGN-FROZEN.md sha256 a3cfcfe14effa987295b7b1b0d3b6d9662a59db92e58aeb6258ef74cf8bd6aad).
# Formal dior-s2anet-s0 input config (sha256 048c1c7e3103463da080f03c50605db492cc28cc7469ff2c9b534db674477dab) with only these changes: test_dataloader.dataset.ann_file, test_dataloader.dataset.data_prefix.img_path, test_evaluator.out_file_path, train_dataloader.dataset.datasets, work_dir.
angle_version = 'le135'
backend_args = None
data_root = 'data/DIOR/'
dataset_type = 'DIORDataset'
default_hooks = {'checkpoint': {'by_epoch': True,
                'interval': 1,
                'max_keep_ckpts': 1,
                'save_best': None,
                'save_last': True,
                'type': 'CheckpointHook'},
 'logger': {'interval': 50, 'type': 'LoggerHook'},
 'param_scheduler': {'type': 'ParamSchedulerHook'},
 'sampler_seed': {'type': 'DistSamplerSeedHook'},
 'timer': {'type': 'IterTimerHook'},
 'visualization': {'type': 'mmdet.DetVisualizationHook'}}
default_scope = 'mmrotate'
env_cfg = {'cudnn_benchmark': False,
 'dist_cfg': {'backend': 'nccl'},
 'mp_cfg': {'mp_start_method': 'fork', 'opencv_num_threads': 0}}
load_from = None
log_level = 'INFO'
log_processor = {'by_epoch': True, 'type': 'LogProcessor', 'window_size': 50}
model = {'backbone': {'depth': 50,
              'frozen_stages': 1,
              'init_cfg': {'checkpoint': 'torchvision://resnet50', 'type': 'Pretrained'},
              'norm_cfg': {'requires_grad': True, 'type': 'BN'},
              'norm_eval': True,
              'num_stages': 4,
              'out_indices': (0, 1, 2, 3),
              'style': 'pytorch',
              'type': 'mmdet.ResNet',
              'zero_init_residual': False},
 'bbox_head_init': {'anchor_generator': {'angle_version': 'le135',
                                         'ratios': [1.0],
                                         'scales': [4],
                                         'strides': [8, 16, 32, 64, 128],
                                         'type': 'FakeRotatedAnchorGenerator'},
                    'bbox_coder': {'angle_version': 'le135',
                                   'edge_swap': False,
                                   'norm_factor': 1,
                                   'proj_xy': True,
                                   'target_means': (0.0, 0.0, 0.0, 0.0, 0.0),
                                   'target_stds': (1.0, 1.0, 1.0, 1.0, 1.0),
                                   'type': 'DeltaXYWHTRBBoxCoder',
                                   'use_box_type': False},
                    'feat_channels': 256,
                    'in_channels': 256,
                    'loss_bbox': {'beta': 0.11, 'loss_weight': 1.0, 'type': 'mmdet.SmoothL1Loss'},
                    'loss_cls': {'alpha': 0.25,
                                 'gamma': 2.0,
                                 'loss_weight': 1.0,
                                 'type': 'mmdet.FocalLoss',
                                 'use_sigmoid': True},
                    'num_classes': 20,
                    'stacked_convs': 2,
                    'type': 'S2AHead'},
 'bbox_head_refine': [{'anchor_generator': {'strides': [8, 16, 32, 64, 128],
                                            'type': 'PseudoRotatedAnchorGenerator'},
                       'bbox_coder': {'angle_version': 'le135',
                                      'edge_swap': False,
                                      'norm_factor': 1,
                                      'proj_xy': True,
                                      'target_means': (0.0, 0.0, 0.0, 0.0, 0.0),
                                      'target_stds': (1.0, 1.0, 1.0, 1.0, 1.0),
                                      'type': 'DeltaXYWHTRBBoxCoder'},
                       'feat_channels': 256,
                       'frm_cfg': {'feat_channels': 256,
                                   'kernel_size': 3,
                                   'strides': [8, 16, 32, 64, 128],
                                   'type': 'AlignConv'},
                       'in_channels': 256,
                       'loss_bbox': {'beta': 0.11, 'loss_weight': 1.0, 'type': 'mmdet.SmoothL1Loss'},
                       'loss_cls': {'alpha': 0.25,
                                    'gamma': 2.0,
                                    'loss_weight': 1.0,
                                    'type': 'mmdet.FocalLoss',
                                    'use_sigmoid': True},
                       'num_classes': 20,
                       'stacked_convs': 2,
                       'type': 'S2ARefineHead'}],
 'data_preprocessor': {'bgr_to_rgb': True,
                       'boxtype2tensor': False,
                       'mean': [123.675, 116.28, 103.53],
                       'pad_size_divisor': 32,
                       'std': [58.395, 57.12, 57.375],
                       'type': 'mmdet.DetDataPreprocessor'},
 'neck': {'add_extra_convs': 'on_input',
          'in_channels': [256, 512, 1024, 2048],
          'num_outs': 5,
          'out_channels': 256,
          'start_level': 1,
          'type': 'mmdet.FPN'},
 'test_cfg': {'max_per_img': 2000,
              'min_bbox_size': 0,
              'nms': {'iou_threshold': 0.1, 'type': 'nms_rotated'},
              'nms_pre': 2000,
              'score_thr': 0.05},
 'train_cfg': {'init': {'allowed_border': -1,
                        'assigner': {'ignore_iof_thr': -1,
                                     'iou_calculator': {'type': 'RBboxOverlaps2D'},
                                     'min_pos_iou': 0,
                                     'neg_iou_thr': 0.4,
                                     'pos_iou_thr': 0.5,
                                     'type': 'mmdet.MaxIoUAssigner'},
                        'debug': False,
                        'pos_weight': -1},
               'refine': [{'allowed_border': -1,
                           'assigner': {'ignore_iof_thr': -1,
                                        'iou_calculator': {'type': 'RBboxOverlaps2D'},
                                        'min_pos_iou': 0,
                                        'neg_iou_thr': 0.4,
                                        'pos_iou_thr': 0.5,
                                        'type': 'mmdet.MaxIoUAssigner'},
                           'debug': False,
                           'pos_weight': -1}],
               'stage_loss_weights': [1.0]},
 'type': 'RefineSingleStageDetector'}
optim_wrapper = {'clip_grad': {'max_norm': 35, 'norm_type': 2},
 'optimizer': {'betas': (0.9, 0.999), 'lr': 0.0001, 'type': 'AdamW', 'weight_decay': 0.05},
 'type': 'OptimWrapper'}
param_scheduler = [{'begin': 0, 'by_epoch': False, 'end': 500, 'start_factor': 0.3333333333333333, 'type': 'LinearLR'},
 {'begin': 0, 'by_epoch': True, 'end': 12, 'gamma': 0.1, 'milestones': [8, 11], 'type': 'MultiStepLR'}]
randomness = {'deterministic': False, 'seed': 0}
resume = False
test_cfg = {'type': 'TestLoop'}
test_dataloader = {'batch_size': 1,
 'dataset': {'ann_file': 'ImageSets/Main/trainval.txt',
             'backend_args': None,
             'data_prefix': {'img_path': 'JPEGImages-trainval'},
             'data_root': '/root/autodl-tmp/rotcert-planB/data/dior/',
             'pipeline': [{'backend_args': None, 'type': 'mmdet.LoadImageFromFile'},
                          {'keep_ratio': True, 'scale': (800, 800), 'type': 'mmdet.Resize'},
                          {'box_type': 'qbox', 'type': 'mmdet.LoadAnnotations', 'with_bbox': True},
                          {'box_type_mapping': {'gt_bboxes': 'rbox'}, 'type': 'ConvertBoxType'},
                          {'meta_keys': ('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'),
                           'type': 'mmdet.PackDetInputs'}],
             'test_mode': True,
             'type': 'DIORDataset'},
 'drop_last': False,
 'num_workers': 2,
 'persistent_workers': True,
 'sampler': {'shuffle': False, 'type': 'DefaultSampler'}}
test_evaluator = {'out_file_path': '/root/autodl-tmp/rotcert-planB/run/jobs/dior-s2anet-s0-trainonly/predictions.pkl',
 'type': 'DumpResults'}
test_pipeline = [{'backend_args': None, 'type': 'mmdet.LoadImageFromFile'},
 {'keep_ratio': True, 'scale': (800, 800), 'type': 'mmdet.Resize'},
 {'meta_keys': ('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'),
  'type': 'mmdet.PackDetInputs'}]
train_cfg = {'max_epochs': 12, 'type': 'EpochBasedTrainLoop', 'val_interval': 13}
train_dataloader = {'batch_sampler': None,
 'batch_size': 2,
 'dataset': {'datasets': [{'ann_file': 'ImageSets/Main/train.txt',
                           'data_prefix': {'img_path': 'JPEGImages-trainval'},
                           'data_root': '/root/autodl-tmp/rotcert-planB/data/dior/',
                           'filter_cfg': {'filter_empty_gt': True},
                           'pipeline': [{'backend_args': None, 'type': 'mmdet.LoadImageFromFile'},
                                        {'box_type': 'qbox',
                                         'type': 'mmdet.LoadAnnotations',
                                         'with_bbox': True},
                                        {'box_type_mapping': {'gt_bboxes': 'rbox'}, 'type': 'ConvertBoxType'},
                                        {'keep_ratio': True, 'scale': (800, 800), 'type': 'mmdet.Resize'},
                                        {'min_gt_bbox_wh': (0.01, 0.01), 'type': 'mmdet.FilterAnnotations'},
                                        {'direction': ['horizontal', 'vertical', 'diagonal'],
                                         'prob': 0.75,
                                         'type': 'mmdet.RandomFlip'},
                                        {'type': 'mmdet.PackDetInputs'}],
                           'type': 'DIORDataset'}],
             'ignore_keys': ['DATASET_TYPE'],
             'type': 'ConcatDataset'},
 'num_workers': 8,
 'persistent_workers': True,
 'sampler': {'shuffle': True, 'type': 'DefaultSampler'}}
train_pipeline = [{'backend_args': None, 'type': 'mmdet.LoadImageFromFile'},
 {'box_type': 'qbox', 'type': 'mmdet.LoadAnnotations', 'with_bbox': True},
 {'box_type_mapping': {'gt_bboxes': 'rbox'}, 'type': 'ConvertBoxType'},
 {'keep_ratio': True, 'scale': (800, 800), 'type': 'mmdet.Resize'},
 {'min_gt_bbox_wh': (0.01, 0.01), 'type': 'mmdet.FilterAnnotations'},
 {'direction': ['horizontal', 'vertical', 'diagonal'], 'prob': 0.75, 'type': 'mmdet.RandomFlip'},
 {'type': 'mmdet.PackDetInputs'}]
val_cfg = None
val_dataloader = None
val_evaluator = None
val_pipeline = [{'backend_args': None, 'type': 'mmdet.LoadImageFromFile'},
 {'keep_ratio': True, 'scale': (800, 800), 'type': 'mmdet.Resize'},
 {'box_type': 'qbox', 'type': 'mmdet.LoadAnnotations', 'with_bbox': True},
 {'box_type_mapping': {'gt_bboxes': 'rbox'}, 'type': 'ConvertBoxType'},
 {'meta_keys': ('img_id', 'img_path', 'ori_shape', 'img_shape', 'scale_factor'),
  'type': 'mmdet.PackDetInputs'}]
vis_backends = [{'type': 'LocalVisBackend'}]
visualizer = {'name': 'visualizer', 'type': 'RotLocalVisualizer', 'vis_backends': [{'type': 'LocalVisBackend'}]}
work_dir = '/root/autodl-tmp/rotcert-planB/run/jobs/dior-s2anet-s0-trainonly'
